myauth/myauth/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from users import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^users/', include('users.urls')),
	url(r'^users/', include('django.contrib.auth.urls')),
	url(r'^index/$', views.index, name='index'),
]

myauth/users/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'users'

urlpatterns = [
	url(r'^register/$', views.register, name='register'), 
	
]

myauth/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
	nickname = models.CharField(max_length=50, blank=True)
	
	class Meta(AbstractUser.Meta):
		pass

myauth/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User

class RegisterForm(UserCreationForm):
	class Meta(UserCreationForm.Meta):
		model = User
		fields = ['username', 'email']

myauth/users/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm


def register(request):
	next = request.GET.get('next', request.POST.get('next', ''))
	if request.method == 'POST':
		form = RegisterForm(request.POST)
		if form.is_valid():
			form.save()
			if next:
				return redirect(next)
			return redirect('/')
	
	else:
		form = RegisterForm()
	return render(request, 'users/register.html', context={'form': form, 'next': next})
	
def index(request):
	return render(request, 'index.html')

myauth/templates/index.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>首页</title>
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
</head>
<body>
<div class="flex-center">
    <div class="container">
        <div>
            <h1 class="logo"><a href="{% url 'index' %}">用户管理系统</a></h1>
            {% if user.is_authenticated %}
                <p>你已登录，欢迎你：<a href="#">{{ user.username }}</a></p>
                <button class="btn btn-default"><a href="{% url 'logout' %}?next={{ request.path }}">注销登录</a>
                </button>
                <button class="btn btn-default"><a href="{% url 'password_change' %}?next={{ request.path }}">修改密码</a>
                </button>
            {% else %}
                <p>你还没有登录，请
                    <button class="btn btn-default"><a href="{% url 'login' %}?next={{ request.path }}">登录</a>
                    </button>
                    或者
                    <button class="btn btn-default"><a href="{% url 'users:register' %}?next={{ request.path }}">注册</a>
                    </button>
                </p>
            {% endif %}
        </div>
    </div>
</div>
</body>
</html>

myauth/templates/users/register.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>注册</title>
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
    <style>
        .errorlist {
            color: red;
        }
    </style>
</head>
<body>
<div class="flex-center">
    <div class="container">
        <div class="flex-center">
            <div class="unit-1-2 unit-1-on-mobile">
                <h1><a href="{% url 'index' %}">用户管理系统</a></h1>
                <h3>注册</h3>
                <form class="form" action="{% url 'users:register' %}" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                        {% if field.help_text %}
                            <p class="help text-small text-muted">{{ field.help_text|safe }}</p>
                        {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-primary btn-block">注册</button>
                    <input type="hidden" name="next" value="{{ next }}"/>
                </form>
                <div class="flex-center top-gap text-small">
                    <a href="{% url 'login' %}">已有账号登录</a>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>